[project]
name = "ruleflow"
version = "0.1.0"
description = "A python framework implementing the Sessie algorithms and Causal Network analysis tools."
requires-python = ">=3.14"
dependencies = [
    "lark",
    "matplotlib",
    "networkx",
    "numpy",
    "numba",
    "platformdirs",
    "psutil",
    "pyvis",
    "pyyaml",
    "regex",
    "rich",
    "textual[syntax]",
    "wcwidth",
    "wolframclient",
]

[dependency-groups]
dev = []
